project:
  type: website
  lib-dir: site_libs
  render:
    - index.qmd

execute:
  freeze: false

editor: source

website:
  title: "Delphi Analysis Notebooks"
  page-footer:
    left: "This work by the [Delphi Research Group](https://delphi.cmu.edu) is licensed under the [MIT license](/LICENSE.md)."
    right: "Supported in part by the [CSTE](https://www.cste.org) and the [CDC](https://www.cdc.gov)."
  navbar:
    pinned: false
    title: "<i class='bi bi-journal-text'></i> Delphi Notebooks"
    right:
      - text: Indicators
        menu:
          - text: "County: Dr. Visits"
            href: indicator_analysis/eval_confirmed_incidence_num_vs_doctor_visits_api_county.html
          - text: "State: HHS vs Dr. Visits"
            href: indicator_analysis/eval_hhs_vs_doctor_visits_api_state.html
      - icon: github
        href: https://github.com/cmu-delphi/analysis-notebooks

format:
  html:
    theme: [cosmo, assets/styles.scss]
